-- ==============================================================================
-- UNIVERSAL COLLECTIONS APP: DATABASE SCHEMA & POLICIES
-- ==============================================================================

-- 1. CLEAN TEARDOWN (SAFETY: COMMENTED OUT)
-- Original production tables (Do not drop):
-- DROP TABLE IF EXISTS template_fields CASCADE;
-- DROP TABLE IF EXISTS collection_templates CASCADE;
-- DROP TABLE IF EXISTS collection_fields CASCADE;
-- DROP TABLE IF EXISTS items CASCADE;
-- DROP TABLE IF EXISTS collections CASCADE;

-- 2. REUSABLE SYSTEM AUDIT TRIGGER FUNCTION
CREATE OR REPLACE FUNCTION update_sys_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.sys_updated_at = NOW();
   RETURN NEW;
END;
$$ LANGUAGE 'plpgsql';

-- 3. COLLECTIONS TABLE (Recursive Categories & Grouping Containers)
CREATE TABLE IF NOT EXISTS collections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id BIGINT REFERENCES collections(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  icon VARCHAR(20) DEFAULT '📁',
  sys_active BOOLEAN DEFAULT true,
  sys_created_by UUID,
  sys_updated_by UUID,
  sys_created_at TIMESTAMPTZ DEFAULT NOW(),
  sys_updated_at TIMESTAMPTZ DEFAULT NOW()
);

DROP TRIGGER IF EXISTS tr_collections_updated_at ON collections;
CREATE TRIGGER tr_collections_updated_at
  BEFORE UPDATE ON collections
  FOR EACH ROW
  EXECUTE FUNCTION update_sys_updated_at_column();

-- 4. MASTER COLLECTION TEMPLATES (Item Type Blueprints)
CREATE TABLE IF NOT EXISTS collection_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  description TEXT,
  icon VARCHAR(50) DEFAULT '📦',
  is_system_preset BOOLEAN NOT NULL DEFAULT true,
  sys_created_at TIMESTAMPTZ DEFAULT NOW(),
  sys_updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. MASTER TEMPLATE FIELDS
CREATE TABLE IF NOT EXISTS template_fields (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id BIGINT NOT NULL REFERENCES collection_templates(id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL,
  label VARCHAR(100) NOT NULL,
  field_type VARCHAR(50) NOT NULL DEFAULT 'text',
  options JSONB DEFAULT '[]'::jsonb,
  is_required BOOLEAN NOT NULL DEFAULT false,
  display_order INT NOT NULL DEFAULT 0,
  sys_created_at TIMESTAMPTZ DEFAULT NOW(),
  sys_updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. COLLECTION FIELDS (Ad-Hoc / Custom Collection-Level Overrides)
CREATE TABLE IF NOT EXISTS collection_fields (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collection_id BIGINT NOT NULL REFERENCES collections(id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL,
  label VARCHAR(100) NOT NULL,
  field_type VARCHAR(50) NOT NULL DEFAULT 'text',
  options JSONB DEFAULT '[]'::jsonb,
  is_required BOOLEAN NOT NULL DEFAULT false,
  display_order INT NOT NULL DEFAULT 0,
  sys_created_at TIMESTAMPTZ DEFAULT NOW(),
  sys_updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. ITEMS TABLE (Decoupled & Item-Centric)
CREATE TABLE IF NOT EXISTS items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collection_id BIGINT REFERENCES collections(id) ON DELETE SET NULL,
  template_id BIGINT REFERENCES collection_templates(id) ON DELETE SET NULL,
  parent_id BIGINT REFERENCES items(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  attributes JSONB DEFAULT '{}'::jsonb,
  sys_active BOOLEAN DEFAULT true,
  sys_created_by UUID,
  sys_updated_by UUID,
  sys_created_at TIMESTAMPTZ DEFAULT NOW(),
  sys_updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

DROP TRIGGER IF EXISTS tr_items_updated_at ON items;
CREATE TRIGGER tr_items_updated_at
  BEFORE UPDATE ON items
  FOR EACH ROW
  EXECUTE FUNCTION update_sys_updated_at_column();

-- Indexes for tree traversal and template filtering performance
CREATE INDEX IF NOT EXISTS idx_items_parent_id ON items(parent_id);
CREATE INDEX IF NOT EXISTS idx_items_collection_id ON items(collection_id);
CREATE INDEX IF NOT EXISTS idx_items_template_id ON items(template_id);
CREATE INDEX IF NOT EXISTS idx_items_attributes_gin ON items USING GIN (attributes);

-- 8. ENABLE ROW LEVEL SECURITY (RLS)
ALTER TABLE collections ENABLE ROW LEVEL SECURITY;
ALTER TABLE collection_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE template_fields ENABLE ROW LEVEL SECURITY;
ALTER TABLE collection_fields ENABLE ROW LEVEL SECURITY;
ALTER TABLE items ENABLE ROW LEVEL SECURITY;

-- 9. DEV ACCESS POLICIES
CREATE POLICY "Public read collections" ON collections FOR SELECT USING (true);
CREATE POLICY "Public insert collections" ON collections FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update collections" ON collections FOR UPDATE USING (true);
CREATE POLICY "Public delete collections" ON collections FOR DELETE USING (true);

CREATE POLICY "Public read collection_templates" ON collection_templates FOR SELECT USING (true);
CREATE POLICY "Public insert collection_templates" ON collection_templates FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update collection_templates" ON collection_templates FOR UPDATE USING (true);
CREATE POLICY "Public delete collection_templates" ON collection_templates FOR DELETE USING (true);

CREATE POLICY "Public read template_fields" ON template_fields FOR SELECT USING (true);
CREATE POLICY "Public insert template_fields" ON template_fields FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update template_fields" ON template_fields FOR UPDATE USING (true);
CREATE POLICY "Public delete template_fields" ON template_fields FOR DELETE USING (true);

CREATE POLICY "Public read collection_fields" ON collection_fields FOR SELECT USING (true);
CREATE POLICY "Public insert collection_fields" ON collection_fields FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update collection_fields" ON collection_fields FOR UPDATE USING (true);
CREATE POLICY "Public delete collection_fields" ON collection_fields FOR DELETE USING (true);

CREATE POLICY "Public read items" ON items FOR SELECT USING (true);
CREATE POLICY "Public insert items" ON items FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update items" ON items FOR UPDATE USING (true);
CREATE POLICY "Public delete items" ON items FOR DELETE USING (true);

-- 10. API ROLES & SEQUENCE GRANTS
GRANT ALL ON TABLE collections TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE collections_id_seq TO anon, authenticated, service_role;

GRANT ALL ON TABLE collection_templates TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE collection_templates_id_seq TO anon, authenticated, service_role;

GRANT ALL ON TABLE template_fields TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE template_fields_id_seq TO anon, authenticated, service_role;

GRANT ALL ON TABLE collection_fields TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE collection_fields_id_seq TO anon, authenticated, service_role;

GRANT ALL ON TABLE items TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE items_id_seq TO anon, authenticated, service_role;

-- 11. SEED MASTER TEMPLATES
INSERT INTO collection_templates (id, name, description, icon, is_system_preset) VALUES
  (1, 'Board Games & Tabletop', 'Strategy board games, expansions, and accessories', '🎲', true),
  (2, 'Trading Card Games (TCG)', 'Pokémon, Magic: The Gathering, sports and graded cards', '🃏', true),
  (3, 'Retro & Modern Video Games', 'Cartridges, disc media, consoles, and accessories', '🎮', true),
  (4, 'Comic Books & Graphic Novels', 'Single issue comic books, trade paperbacks, and slabs', '📚', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO template_fields (template_id, name, label, field_type, options, is_required, display_order) VALUES
  -- Board Games
  (1, 'player_count', 'Player Count', 'number', '[]'::jsonb, false, 1),
  (1, 'play_time', 'Playing Time (Mins)', 'number', '[]'::jsonb, false, 2),
  (1, 'designer', 'Game Designer', 'text', '[]'::jsonb, false, 3),
  (1, 'condition', 'Box Condition', 'select', '["Mint", "Near Mint", "Good", "Worn"]'::jsonb, false, 4),
  (1, 'is_sleeved', 'Cards Sleeved', 'boolean', '[]'::jsonb, false, 5),

  -- Trading Cards
  (2, 'set_name', 'Set / Edition', 'text', '[]'::jsonb, false, 1),
  (2, 'card_number', 'Card Number', 'text', '[]'::jsonb, false, 2),
  (2, 'rarity', 'Rarity', 'select', '["Common", "Uncommon", "Rare", "Ultra Rare", "Secret Rare"]'::jsonb, false, 3),
  (2, 'is_graded', 'Is Graded (Slabbed)', 'boolean', '[]'::jsonb, false, 4),
  (2, 'grading_company', 'Grading Company', 'select', '["PSA", "BGS (Beckett)", "CGC", "Ungraded"]'::jsonb, false, 5),
  (2, 'grade_score', 'Grade Score (1-10)', 'number', '[]'::jsonb, false, 6),

  -- Video Games
  (3, 'platform', 'Console / Platform', 'select', '["Nintendo Switch", "NES / SNES", "PlayStation", "Xbox", "Sega Genesis", "PC"]'::jsonb, true, 1),
  (3, 'release_year', 'Release Year', 'number', '[]'::jsonb, false, 2),
  (3, 'completeness', 'Completeness', 'select', '["Complete in Box (CIB)", "Box + Game", "Cartridge/Disc Only", "Sealed"]'::jsonb, false, 3),
  (3, 'region', 'Region Code', 'select', '["NTSC-U (NA)", "PAL (EU)", "NTSC-J (Japan)"]'::jsonb, false, 4),

  -- Comic Books
  (4, 'publisher', 'Publisher', 'select', '["Marvel", "DC Comics", "Image", "Dark Horse", "IDW", "Indie"]'::jsonb, true, 1),
  (4, 'issue_number', 'Issue #', 'number', '[]'::jsonb, true, 2),
  (4, 'publication_year', 'Publication Year', 'number', '[]'::jsonb, false, 3),
  (4, 'cgc_grade', 'Grade / Condition', 'select', '["9.8 Near Mint/Mint", "9.0 Very Fine/Near Mint", "8.0 Very Fine", "6.0 Fine", "Raw Reader Copy"]'::jsonb, false, 4)
ON CONFLICT (id) DO NOTHING;

-- 12. SEED INITIAL COLLECTIONS (Curated User Collections Only)
INSERT INTO collections (id, parent_id, name, description, icon)
OVERRIDING SYSTEM VALUE
VALUES 
  (1, NULL, 'Test Collection', 'A test collection with nested item hierarchy', '📁')
ON CONFLICT (id) DO NOTHING;

-- 13. SEED ITEMS (Board Games are Category Items; Item 4 is in Test Collection)
INSERT INTO items (id, collection_id, template_id, parent_id, name, attributes)
OVERRIDING SYSTEM VALUE
VALUES 
  (1, NULL, 1, NULL, 'Nemesis Core Game', '{"designer": "Adam Kwapiński", "player_count": 5, "condition": "Near Mint"}'::jsonb),
  (2, NULL, 1, 1, 'Intruder Queen Miniature', '{"scale": "32mm", "is_painted": false}'::jsonb),
  (3, NULL, 1, 1, 'Action Card Deck', '{"card_count": 110, "is_sleeved": true}'::jsonb),
  (4, 1, NULL, NULL, 'Test Collection Item', '{"note": "Curated item inside Test Collection"}'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- 14. SYNCHRONIZE IDENTITY SEQUENCES
SELECT setval(pg_get_serial_sequence('collections', 'id'), COALESCE((SELECT MAX(id) FROM collections), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('collection_templates', 'id'), COALESCE((SELECT MAX(id) FROM collection_templates), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('template_fields', 'id'), COALESCE((SELECT MAX(id) FROM template_fields), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('collection_fields', 'id'), COALESCE((SELECT MAX(id) FROM collection_fields), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('items', 'id'), COALESCE((SELECT MAX(id) FROM items), 0) + 1, false);