-- ==============================================================================
-- UNIVERSAL COLLECTIONS APP: PARALLEL V2 DATABASE SCHEMA & POLICIES
-- ==============================================================================

-- 1. CLEAN TEARDOWN (SAFETY: COMMENTED OUT)
-- -- Original production tables (Do not drop):
-- DROP TABLE IF EXISTS template_fields CASCADE;
-- DROP TABLE IF EXISTS collection_templates CASCADE;
-- DROP TABLE IF EXISTS collection_fields CASCADE;
-- DROP TABLE IF EXISTS items CASCADE;
-- DROP TABLE IF EXISTS collections CASCADE;

-- -- V2 parallel tables (Uncomment only if resetting V2 in the future):
-- DROP TABLE IF EXISTS template_fields2 CASCADE;
-- DROP TABLE IF EXISTS collection_templates2 CASCADE;
-- DROP TABLE IF EXISTS collection_fields2 CASCADE;
-- DROP TABLE IF EXISTS items2 CASCADE;
-- DROP TABLE IF EXISTS collections2 CASCADE;

-- 2. REUSABLE SYSTEM AUDIT TRIGGER FUNCTION
CREATE OR REPLACE FUNCTION update_sys_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.sys_updated_at = NOW();
   RETURN NEW;
END;
$$ LANGUAGE 'plpgsql';

-- 3. COLLECTIONS V2 TABLE (Recursive Folders & Grouping Containers)
CREATE TABLE IF NOT EXISTS collections2 (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id BIGINT REFERENCES collections2(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  icon VARCHAR(20) DEFAULT '📁',
  sys_active BOOLEAN DEFAULT true,
  sys_created_by UUID,
  sys_updated_by UUID,
  sys_created_at TIMESTAMPTZ DEFAULT NOW(),
  sys_updated_at TIMESTAMPTZ DEFAULT NOW()
);

DROP TRIGGER IF EXISTS tr_collections2_updated_at ON collections2;
CREATE TRIGGER tr_collections2_updated_at
  BEFORE UPDATE ON collections2
  FOR EACH ROW
  EXECUTE FUNCTION update_sys_updated_at_column();

-- 4. MASTER COLLECTION TEMPLATES V2 (Item Type Blueprints)
CREATE TABLE IF NOT EXISTS collection_templates2 (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  description TEXT,
  icon VARCHAR(50) DEFAULT '📦',
  is_system_preset BOOLEAN NOT NULL DEFAULT true,
  sys_created_at TIMESTAMPTZ DEFAULT NOW(),
  sys_updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. MASTER TEMPLATE FIELDS V2
CREATE TABLE IF NOT EXISTS template_fields2 (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id BIGINT NOT NULL REFERENCES collection_templates2(id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL,
  label VARCHAR(100) NOT NULL,
  field_type VARCHAR(50) NOT NULL DEFAULT 'text',
  options JSONB DEFAULT '[]'::jsonb,
  is_required BOOLEAN NOT NULL DEFAULT false,
  display_order INT NOT NULL DEFAULT 0,
  sys_created_at TIMESTAMPTZ DEFAULT NOW(),
  sys_updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. COLLECTION FIELDS V2 (Ad-Hoc / Custom Collection-Level Overrides)
CREATE TABLE IF NOT EXISTS collection_fields2 (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collection_id BIGINT NOT NULL REFERENCES collections2(id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL,
  label VARCHAR(100) NOT NULL,
  field_type VARCHAR(50) NOT NULL DEFAULT 'text',
  options JSONB DEFAULT '[]'::jsonb,
  is_required BOOLEAN NOT NULL DEFAULT false,
  display_order INT NOT NULL DEFAULT 0,
  sys_created_at TIMESTAMPTZ DEFAULT NOW(),
  sys_updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. ITEMS V2 TABLE (Decoupled & Item-Centric)
CREATE TABLE IF NOT EXISTS items2 (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collection_id BIGINT REFERENCES collections2(id) ON DELETE SET NULL,
  template_id BIGINT REFERENCES collection_templates2(id) ON DELETE SET NULL,
  parent_id BIGINT REFERENCES items2(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  attributes JSONB DEFAULT '{}'::jsonb,
  sys_active BOOLEAN DEFAULT true,
  sys_created_by UUID,
  sys_updated_by UUID,
  sys_created_at TIMESTAMPTZ DEFAULT NOW(),
  sys_updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

DROP TRIGGER IF EXISTS tr_items2_updated_at ON items2;
CREATE TRIGGER tr_items2_updated_at
  BEFORE UPDATE ON items2
  FOR EACH ROW
  EXECUTE FUNCTION update_sys_updated_at_column();

-- Indexes for tree traversal and template filtering performance
CREATE INDEX IF NOT EXISTS idx_items2_parent_id ON items2(parent_id);
CREATE INDEX IF NOT EXISTS idx_items2_collection_id ON items2(collection_id);
CREATE INDEX IF NOT EXISTS idx_items2_template_id ON items2(template_id);
CREATE INDEX IF NOT EXISTS idx_items2_attributes_gin ON items2 USING GIN (attributes);

-- 8. ENABLE ROW LEVEL SECURITY (RLS)
ALTER TABLE collections2 ENABLE ROW LEVEL SECURITY;
ALTER TABLE collection_templates2 ENABLE ROW LEVEL SECURITY;
ALTER TABLE template_fields2 ENABLE ROW LEVEL SECURITY;
ALTER TABLE collection_fields2 ENABLE ROW LEVEL SECURITY;
ALTER TABLE items2 ENABLE ROW LEVEL SECURITY;

-- 9. DEV ACCESS POLICIES
CREATE POLICY "Public read collections2" ON collections2 FOR SELECT USING (true);
CREATE POLICY "Public insert collections2" ON collections2 FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update collections2" ON collections2 FOR UPDATE USING (true);
CREATE POLICY "Public delete collections2" ON collections2 FOR DELETE USING (true);

CREATE POLICY "Public read collection_templates2" ON collection_templates2 FOR SELECT USING (true);
CREATE POLICY "Public insert collection_templates2" ON collection_templates2 FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update collection_templates2" ON collection_templates2 FOR UPDATE USING (true);
CREATE POLICY "Public delete collection_templates2" ON collection_templates2 FOR DELETE USING (true);

CREATE POLICY "Public read template_fields2" ON template_fields2 FOR SELECT USING (true);
CREATE POLICY "Public insert template_fields2" ON template_fields2 FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update template_fields2" ON template_fields2 FOR UPDATE USING (true);
CREATE POLICY "Public delete template_fields2" ON template_fields2 FOR DELETE USING (true);

CREATE POLICY "Public read collection_fields2" ON collection_fields2 FOR SELECT USING (true);
CREATE POLICY "Public insert collection_fields2" ON collection_fields2 FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update collection_fields2" ON collection_fields2 FOR UPDATE USING (true);
CREATE POLICY "Public delete collection_fields2" ON collection_fields2 FOR DELETE USING (true);

CREATE POLICY "Public read items2" ON items2 FOR SELECT USING (true);
CREATE POLICY "Public insert items2" ON items2 FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update items2" ON items2 FOR UPDATE USING (true);
CREATE POLICY "Public delete items2" ON items2 FOR DELETE USING (true);

-- 10. API ROLES & SEQUENCE GRANTS
GRANT ALL ON TABLE collections2 TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE collections2_id_seq TO anon, authenticated, service_role;

GRANT ALL ON TABLE collection_templates2 TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE collection_templates2_id_seq TO anon, authenticated, service_role;

GRANT ALL ON TABLE template_fields2 TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE template_fields2_id_seq TO anon, authenticated, service_role;

GRANT ALL ON TABLE collection_fields2 TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE collection_fields2_id_seq TO anon, authenticated, service_role;

GRANT ALL ON TABLE items2 TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE items2_id_seq TO anon, authenticated, service_role;

-- 11. SEED MASTER TEMPLATES V2
INSERT INTO collection_templates2 (id, name, description, icon, is_system_preset) VALUES
  (1, 'Board Games & Tabletop', 'Strategy board games, expansions, and accessories', '🎲', true),
  (2, 'Trading Card Games (TCG)', 'Pokémon, Magic: The Gathering, sports and graded cards', '🃏', true),
  (3, 'Retro & Modern Video Games', 'Cartridges, disc media, consoles, and accessories', '🎮', true),
  (4, 'Comic Books & Graphic Novels', 'Single issue comic books, trade paperbacks, and slabs', '📚', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO template_fields2 (template_id, name, label, field_type, options, is_required, display_order) VALUES
  -- Board Games
  (1, 'player_count', 'Player Count', 'number', '[]'::jsonb, false, 1),
  (1, 'play_time', 'Playing Time (Mins)', 'number', '[]'::jsonb, false, 2),
  (1, 'designer', 'Game Designer', 'text', '[]'::jsonb, false, 3),
  (1, 'condition', 'Box Condition', 'select', '["Mint", "Near Mint", "Good", "Worn"]'::jsonb, false, 4),
  (1, 'is_sleeved', 'Cards Sleeved', 'boolean', '[]'::jsonb, false, 5),

  -- Trading Cards
  (2, 'set_name', 'Set / Edition', 'text', '[]'::jsonb, false, 1),
  (2, 'card_number', 'Card Number', 'text', '[]'::jsonb, false, 2),
  (2, 'rarity', 'Rarity', 'select', '["Common", "Uncommon", "Rare", "Ultra Rare", "Secret Rare"]'::jsonb, false, 3),
  (2, 'is_graded', 'Is Graded (Slabbed)', 'boolean', '[]'::jsonb, false, 4),
  (2, 'grading_company', 'Grading Company', 'select', '["PSA", "BGS (Beckett)", "CGC", "Ungraded"]'::jsonb, false, 5),
  (2, 'grade_score', 'Grade Score (1-10)', 'number', '[]'::jsonb, false, 6),

  -- Video Games
  (3, 'platform', 'Console / Platform', 'select', '["Nintendo Switch", "NES / SNES", "PlayStation", "Xbox", "Sega Genesis", "PC"]'::jsonb, true, 1),
  (3, 'release_year', 'Release Year', 'number', '[]'::jsonb, false, 2),
  (3, 'completeness', 'Completeness', 'select', '["Complete in Box (CIB)", "Box + Game", "Cartridge/Disc Only", "Sealed"]'::jsonb, false, 3),
  (3, 'region', 'Region Code', 'select', '["NTSC-U (NA)", "PAL (EU)", "NTSC-J (Japan)"]'::jsonb, false, 4),

  -- Comic Books
  (4, 'publisher', 'Publisher', 'select', '["Marvel", "DC Comics", "Image", "Dark Horse", "IDW", "Indie"]'::jsonb, true, 1),
  (4, 'issue_number', 'Issue #', 'number', '[]'::jsonb, true, 2),
  (4, 'publication_year', 'Publication Year', 'number', '[]'::jsonb, false, 3),
  (4, 'cgc_grade', 'Grade / Condition', 'select', '["9.8 Near Mint/Mint", "9.0 Very Fine/Near Mint", "8.0 Very Fine", "6.0 Fine", "Raw Reader Copy"]'::jsonb, false, 4)
ON CONFLICT (id) DO NOTHING;

-- 12. SEED INITIAL COLLECTIONS V2 (Curated User Collections Only)
INSERT INTO collections2 (id, parent_id, name, description, icon)
OVERRIDING SYSTEM VALUE
VALUES 
  (1, NULL, 'Test Collection', 'A test collection with nested item hierarchy', '📁')
ON CONFLICT (id) DO NOTHING;

-- 13. SEED ITEMS V2 (Board Games are Category Items; Item 4 is in Test Collection)
INSERT INTO items2 (id, collection_id, template_id, parent_id, name, attributes)
OVERRIDING SYSTEM VALUE
VALUES 
  (1, NULL, 1, NULL, 'Nemesis Core Game', '{"designer": "Adam Kwapiński", "player_count": 5, "condition": "Near Mint"}'::jsonb),
  (2, NULL, 1, 1, 'Intruder Queen Miniature', '{"scale": "32mm", "is_painted": false}'::jsonb),
  (3, NULL, 1, 1, 'Action Card Deck', '{"card_count": 110, "is_sleeved": true}'::jsonb),
  (4, 1, NULL, NULL, 'Test Collection Item', '{"note": "Curated item inside Test Collection"}'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- 14. SYNCHRONIZE IDENTITY SEQUENCES
SELECT setval(pg_get_serial_sequence('collections2', 'id'), COALESCE((SELECT MAX(id) FROM collections2), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('collection_templates2', 'id'), COALESCE((SELECT MAX(id) FROM collection_templates2), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('template_fields2', 'id'), COALESCE((SELECT MAX(id) FROM template_fields2), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('collection_fields2', 'id'), COALESCE((SELECT MAX(id) FROM collection_fields2), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('items2', 'id'), COALESCE((SELECT MAX(id) FROM items2), 0) + 1, false);