-- ==============================================================================
-- UNIVERSAL COLLECTIONS APP: FULL DATABASE SCHEMA & POLICIES (WITH TEMPLATES)
-- ==============================================================================

-- 1. CLEAN TEARDOWN (Drop in reverse foreign key order)
DROP TABLE IF EXISTS template_fields CASCADE;
DROP TABLE IF EXISTS collection_templates CASCADE;
DROP TABLE IF EXISTS collection_fields CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS collections CASCADE;

-- 2. CREATE COLLECTIONS TABLE
CREATE TABLE collections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  sys_created_by UUID,
  sys_updated_by UUID,
  sys_created_at TIMESTAMPTZ DEFAULT NOW(),
  sys_updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. CREATE COLLECTION FIELDS TEMPLATE TABLE
CREATE TABLE collection_fields (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collection_id BIGINT NOT NULL REFERENCES collections(id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL,
  label VARCHAR(100) NOT NULL,
  field_type VARCHAR(50) NOT NULL DEFAULT 'text',
  options JSONB DEFAULT '[]'::jsonb,
  is_required BOOLEAN NOT NULL DEFAULT false,
  display_order INT NOT NULL DEFAULT 0,
  sys_created_at TIMESTAMPTZ DEFAULT NOW(),
  sys_updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. CREATE COLLECTION TEMPLATES TABLE
CREATE TABLE collection_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  description TEXT,
  icon VARCHAR(50) DEFAULT '📑',
  sys_created_at TIMESTAMPTZ DEFAULT NOW(),
  sys_updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. CREATE TEMPLATE FIELDS TABLE
CREATE TABLE template_fields (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id BIGINT NOT NULL REFERENCES collection_templates(id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL,
  label VARCHAR(100) NOT NULL,
  field_type VARCHAR(50) NOT NULL DEFAULT 'text',
  options JSONB DEFAULT '[]'::jsonb,
  is_required BOOLEAN NOT NULL DEFAULT false,
  display_order INT NOT NULL DEFAULT 0,
  sys_created_at TIMESTAMPTZ DEFAULT NOW(),
  sys_updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. CREATE ITEMS HIERARCHICAL TABLE
CREATE TABLE items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collection_id BIGINT NOT NULL REFERENCES collections(id) ON DELETE CASCADE,
  parent_id BIGINT REFERENCES items(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  attributes JSONB DEFAULT '{}'::jsonb,
  sys_created_by UUID,
  sys_updated_by UUID,
  sys_created_at TIMESTAMPTZ DEFAULT NOW(),
  sys_updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. ENABLE ROW LEVEL SECURITY (RLS)
ALTER TABLE collections ENABLE ROW LEVEL SECURITY;
ALTER TABLE collection_fields ENABLE ROW LEVEL SECURITY;
ALTER TABLE collection_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE template_fields ENABLE ROW LEVEL SECURITY;
ALTER TABLE items ENABLE ROW LEVEL SECURITY;

-- 8. CREATE DEV POLICIES
CREATE POLICY "Public read collections" ON collections FOR SELECT USING (true);
CREATE POLICY "Public insert collections" ON collections FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update collections" ON collections FOR UPDATE USING (true);
CREATE POLICY "Public delete collections" ON collections FOR DELETE USING (true);

CREATE POLICY "Public read collection fields" ON collection_fields FOR SELECT USING (true);
CREATE POLICY "Public insert collection fields" ON collection_fields FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update collection fields" ON collection_fields FOR UPDATE USING (true);
CREATE POLICY "Public delete collection fields" ON collection_fields FOR DELETE USING (true);

CREATE POLICY "Public read collection templates" ON collection_templates FOR SELECT USING (true);
CREATE POLICY "Public insert collection templates" ON collection_templates FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update collection templates" ON collection_templates FOR UPDATE USING (true);
CREATE POLICY "Public delete collection templates" ON collection_templates FOR DELETE USING (true);

CREATE POLICY "Public read template fields" ON template_fields FOR SELECT USING (true);
CREATE POLICY "Public insert template fields" ON template_fields FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update template fields" ON template_fields FOR UPDATE USING (true);
CREATE POLICY "Public delete template fields" ON template_fields FOR DELETE USING (true);

CREATE POLICY "Public read items" ON items FOR SELECT USING (true);
CREATE POLICY "Public insert items" ON items FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update items" ON items FOR UPDATE USING (true);
CREATE POLICY "Public delete items" ON items FOR DELETE USING (true);

-- 9. GRANT FULL API ACCESS ROLES & SEQUENCES
GRANT ALL ON TABLE collections TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE collections_id_seq TO anon, authenticated, service_role;

GRANT ALL ON TABLE collection_fields TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE collection_fields_id_seq TO anon, authenticated, service_role;

GRANT ALL ON TABLE collection_templates TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE collection_templates_id_seq TO anon, authenticated, service_role;

GRANT ALL ON TABLE template_fields TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE template_fields_id_seq TO anon, authenticated, service_role;

GRANT ALL ON TABLE items TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE items_id_seq TO anon, authenticated, service_role;

-- 10. SEED INITIAL BASELINE DATA
INSERT INTO collections (id, name, description)
VALUES (1, 'Board Games', 'Modern tabletop and strategy games');

INSERT INTO collection_fields (collection_id, name, label, field_type, options, is_required, display_order)
VALUES 
  (1, 'player_count', 'Player Count', 'number', '[]'::jsonb, false, 1),
  (1, 'condition', 'Condition', 'select', '["Mint", "Near Mint", "Good", "Worn"]'::jsonb, false, 2),
  (1, 'is_sleeved', 'Cards Sleeved', 'boolean', '[]'::jsonb, false, 3);

INSERT INTO collections (id, name, description)
OVERRIDING SYSTEM VALUE
VALUES (2, 'Test Collection', 'A test collection with nested item hierarchy');

-- Root Items (parent_id = NULL)
INSERT INTO items (id, collection_id, parent_id, name, attributes)
OVERRIDING SYSTEM VALUE
VALUES 
  (1, 2, NULL, 'Item 1', '{"condition": "Mint", "rarity": "Common"}'::jsonb),
  (2, 2, NULL, 'Item 2', '{"condition": "Good", "rarity": "Uncommon"}'::jsonb),
  (3, 2, NULL, 'Item 3', '{"condition": "Near Mint", "rarity": "Rare"}'::jsonb);

-- Sub-Items under Item 3 (id: 3)
INSERT INTO items (id, collection_id, parent_id, name, attributes)
OVERRIDING SYSTEM VALUE
VALUES 
  (4, 2, 3, 'Sub-item 3A (Part 1)', '{"part_number": "A-01"}'::jsonb),
  (5, 2, 3, 'Sub-item 3B (Part 2)', '{"part_number": "A-02"}'::jsonb);

-- Sub-sub-item under Sub-item 3B (id: 5)
INSERT INTO items (id, collection_id, parent_id, name, attributes)
OVERRIDING SYSTEM VALUE
VALUES 
  (6, 2, 5, 'Sub-sub-item 3B', '{"scale": "1:18"}'::jsonb);